CREATE SCHEMA IF NOT EXISTS xcommerce;

GRANT USAGE ON SCHEMA xcommerce TO igorlema;

ALTER DEFAULT PRIVILEGES
   IN SCHEMA xcommerce
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES
   TO igorlema;

ALTER DEFAULT PRIVILEGES
   IN SCHEMA xcommerce
GRANT USAGE ON SEQUENCES
   TO igorlema;
